"""
Hand check of one labeling RL decision: one planted test vehicle, second by second, raw inputs, index
features, running reference AI, policy probabilities and action, with the first second recomputed by hand.

    python scripts/rl_decision_trace.py [--label aggressive] [--k 0] [--proximity metres|headway] [--policy TAG]

Policy: data/labeling_rl_planted<TAG>_ppo_seed0.zip (scripts/train_labeling_rl_planted.py), features matching
--proximity. Vehicle: the k-th test vehicle of highway_medium seed 7 (a test seed) with the given true label, at
least 60 s, and a car ahead within 50 m in its first second (so the proximity term is checked).
Writes docs/hand_checks/rl_decision_trace[_<proximity>]_<label>.md.
"""
import argparse
import os
import sys
import warnings

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from paths import DATA_DIR, ROOT  # noqa: E402
from env.labeling_env import LabelingEnv, planted_sequences, reference_ai  # noqa: E402
from model.aggressiveness_model import THW_MAX_S, WEIGHTS, headway_features, index_features  # noqa: E402

CLASSES = ("conservative", "normal", "aggressive")
RUN = os.path.join(DATA_DIR, "sumo_planted", "highway_medium_s7.per_second.csv.gz")


def main(label, k, proximity, policy):
    import torch
    from stable_baselines3 import PPO
    policy_file = f"labeling_rl_planted{policy}_ppo_seed0.zip"
    model = PPO.load(os.path.join(DATA_DIR, policy_file))
    feats = headway_features if proximity == "headway" else index_features
    ps = pd.read_csv(RUN)
    ps = ps[ps["speed_kmh"] >= 5.0]
    first_gap = ps.groupby("vehicle_id")["gap_m"].first()
    seqs = [s for s in planted_sequences([RUN], features=feats) if s["label"] == label and len(s["features"]) >= 60
            and 0 < first_gap[s["driver"]] <= 50]
    s = seqs[k]
    raw = ps[ps["vehicle_id"] == s["driver"]].reset_index(drop=True)
    env = LabelingEnv([s], CLASSES, horizon=60, wait_cost=0.002)
    obs, _ = env.reset(options={"seq": 0, "t0": 0})
    rows, done, total = [], False, 0.0
    while not done:
        with torch.no_grad():
            p = model.policy.get_distribution(model.policy.obs_to_tensor(obs)[0]).distribution.probs.numpy()[0]
        action, _ = model.predict(obs, deterministic=True)
        n = env.n
        r = raw.iloc[n - 1]
        rows.append({"second": n, "speed_kmh": r["speed_kmh"], "accel": r["accel"], "gap_m": r["gap_m"],
                     "wave_m": r["wave_m"], **{f"f{i}": s["features"][n - 1, i] for i in range(4)},
                     "AI_run": 100 * obs[8], "AI_recent": 100 * obs[9],
                     "p_wait": p[0], "p_cons": p[1], "p_norm": p[2], "p_aggr": p[3],
                     "action": ["wait", *CLASSES][int(action)]})
        obs, reward, done, _, info = env.step(int(action))
        total += reward
    t = pd.DataFrame(rows)

    # first second by hand
    r0 = raw.iloc[0]
    ns = min(r0["speed_kmh"] / 150, 1.0)
    na = min(abs(r0["accel"]) / 5, 1.0)
    if proximity == "headway":
        thw = r0["gap_m"] / (r0["speed_kmh"] / 3.6)
        npx = 1 - thw / THW_MAX_S if 0 < thw <= THW_MAX_S else 0.0
        prox_line = (f"- gap {r0['gap_m']:.4f} m at {r0['speed_kmh'] / 3.6:.4f} m/s: headway {thw:.4f} s, "
                     f"1 - {thw:.4f} / {THW_MAX_S:g} = {npx:.4f}, squared {npx ** 2:.4f}" if npx > 0
                     else f"- headway {thw:.4f} s: above {THW_MAX_S:g} s, term 0")
    else:
        npx = 1 - r0["gap_m"] / 50 if 0 < r0["gap_m"] <= 50 else 0.0
        prox_line = (f"- gap {r0['gap_m']:.4f} m: 1 - {r0['gap_m']:.4f} / 50 = {npx:.4f}, squared {npx ** 2:.4f}" if npx > 0
                     else f"- gap {r0['gap_m']:.4f} m: no car within 50 m, term 0")
    nw = min(abs(r0["wave_m"]) / 1.5, 1.0)
    hand = np.array([ns ** 2, na, npx ** 2, nw])
    ai_hand = 100 * float((hand * np.array(WEIGHTS)).sum())
    assert np.allclose(hand, s["features"][0], atol=1e-9), (hand, s["features"][0])
    assert abs(ai_hand - t["AI_run"].iloc[0]) < 1e-3
    run_last = 100 * reference_ai(s["features"][:len(t)].mean(axis=0))
    assert abs(run_last - t["AI_run"].iloc[-1]) < 1e-3

    lines = [
        "# hand check: one labeling RL decision",
        "",
        f"policy `data/{policy_file}` (proximity {proximity}, wait cost 0.002, horizon 60 s). vehicle `{s['driver']}`, "
        f"true type {label}, `highway_medium` seed 7 (test seed, never seen in training), {len(s['features'])} s above 5 km/h. "
        "generated by `scripts/rl_decision_trace.py`.",
        "",
        "## first second by hand",
        "",
        f"- speed {r0['speed_kmh']:.4f} km/h / 150 = {r0['speed_kmh'] / 150:.4f}, squared {ns ** 2:.4f}",
        f"- accel |{r0['accel']:.4f}| m/s2 / 5 = {na:.4f}",
        prox_line,
        f"- wave |{r0['wave_m']:.4f}| m / 1.5 = {nw:.4f}",
        f"- AI = 100 x (0.5 x {hand[0]:.4f} + 0.2 x {hand[1]:.4f} + 0.8 x {hand[2]:.4f} + 0.4 x {hand[3]:.4f}) = {ai_hand:.2f}",
        f"- code: features {np.round(s['features'][0], 4).tolist()}, running AI {t['AI_run'].iloc[0]:.2f} (match)",
        "",
        "## second by second",
        "",
        "| s | speed km/h | accel | gap m | wave m | AI running | AI last 10 s | p wait | p cons | p norm | p aggr | action |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in t.itertuples():
        lines.append(f"| {r.second} | {r.speed_kmh:.1f} | {r.accel:.2f} | {r.gap_m:.1f} | {r.wave_m:.2f} | {r.AI_run:.1f} | "
                     f"{r.AI_recent:.1f} | {r.p_wait:.2f} | {r.p_cons:.2f} | {r.p_norm:.2f} | {r.p_aggr:.2f} | {r.action} |")
    final = t.iloc[-1]
    lines += ["", "## decision", "",
              f"label {final['action']} after {int(final['second'])} s (true {label}); running AI at the decision "
              f"{final['AI_run']:.1f} = reference AI of the mean of the {int(final['second'])} feature rows "
              f"(recomputed: {run_last:.1f}). episode reward {total:+.3f} = "
              f"{'+1' if final['action'] == label else '-1'} - 0.002 x {int(final['second']) - 1} waits."]
    out = os.path.join(ROOT, "docs", "hand_checks", "rl_decision_trace" + ("" if proximity == "metres" else f"_{proximity}") + f"_{label}.md")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    warnings.simplefilter("ignore")
    p = argparse.ArgumentParser()
    p.add_argument("--label", default="aggressive", choices=CLASSES)
    p.add_argument("--k", type=int, default=0)
    p.add_argument("--proximity", choices=["metres", "headway"], default="headway")
    p.add_argument("--policy", default="_headway_wb4", help="tag of the saved policy ('' = metres, gamma 1, no wait bias)")
    a = p.parse_args()
    main(a.label, a.k, a.proximity, a.policy)
